version: '3.8'

services:
  bind9:
    image: ubuntu/bind9:latest
    build:
      context: ./bind9
      dockerfile: Dockerfile
    container_name: bind9
    volumes:
      - ./bind9:/etc/bind
      - ./bind9/zones:/etc/bind/zones  # Mounted zones directory
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dns_network:
        ipv4_address: 172.18.0.2
    environment:
      - RNDC_KEY=/etc/bind/rndc.key  # Can be removed if not used elsewhere
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dnsdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - NPM_API_URL=http://nginx-proxy-manager:81/api
      - NPM_API_KEY=your_valid_api_key_here

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      dns_network:
        ipv4_address: 172.18.0.3

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dns_network:
        ipv4_address: 172.18.0.4

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  postgres_data:
