services:
  bind9:
    image: internetsystemsconsortium/bind9:9.16
    container_name: bind9
    volumes:
      - ./bind9:/etc/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data

  dns_manager:
    build: ./manager
    container_name: dns_manager
    env_file:
      - .env
    volumes:
      - ./manager:/app
    depends_on:
      - postgres
      - bind9
      - nginx-proxy-manager
