version: '3.8'

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    volumes:
      - ./bind9:/etc/bind
      - ./bind9/rndc.key:/etc/bind/rndc.key  # Mounted rndc key
      - ./bind9/zones:/etc/bind/zones       # Mounted zones directory
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dns_network:
        ipv4_address: 172.18.0.2
    command: /usr/sbin/named -f -c /etc/bind/named.conf -u bind
    environment:
      - RNDC_KEY=/etc/bind/rndc.key

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      dns_network:
        ipv4_address: 172.18.0.3

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dns_network:
        ipv4_address: 172.18.0.4

  dns_manager:
    build: ./manager
    container_name: dns_manager
    env_file:
      - .env
    volumes:
      - ./manager:/app
      - ./bind9/rndc.key:/etc/bind/rndc.key  # Access rndc key if needed
    depends_on:
      - postgres
      - bind9
      - nginx-proxy-manager
    networks:
      dns_network:
        ipv4_address: 172.18.0.5

networks:
  dns_network:
    driver: bridge
    ipam:

      config:
        - subnet: 172.18.0.0/16

volumes:
  postgres_data:
